from enum import Enum

class Intent(str, Enum):
    GREETING = "GREETING"
    LIST_INCIDENTS = "LIST_INCIDENTS"
    GET_INCIDENT = "GET_INCIDENT"
    GET_INCIDENT_STATS = "GET_INCIDENT_STATS"
    LIST_USERS = "LIST_USERS"
    LIST_EMPLOYEES = "LIST_EMPLOYEES"
    LIST_WORKERS = "LIST_WORKERS"
    GET_USERS_STATS = "GET_USERS_STATS"
    GET_ME = "GET_ME"
    LIST_WORK_ORDERS = "LIST_WORK_ORDERS"
    GET_WORK_STATS = "GET_WORK_STATS"
    UNKNOWN = "UNKNOWN"
